name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: List project files for debugging
        run: |
          echo "Project directory structure:"
          find . -maxdepth=2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

      - name: Run tests
        id: run_tests
        run: |
          pytest tests/ --maxfail=1 --disable-warnings -q
        # Allow subsequent steps to run even if tests fail
        continue-on-error: true

      - name: Log error details if any issue occurs
        if: failure()
        run: |
          echo "⚠️ An error occurred during the CI run. Logging additional information..."
          echo "=== Environment Variables ==="
          printenv
          echo "=== Directory Listing ==="
          ls -al
          echo "=== End of Log ==="

      - name: Fail build if tests failed
        if: failure()
        run: exit 1
