 name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: List project files (Debug)
        run: |
          echo "Listing project files recursively for debugging:"
          ls -alR

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

      - name: Run tests
        id: run_tests
        continue-on-error: true
        run: |
          echo "Running tests..."
          # Capture the test output to a log file for later inspection if needed.
          pytest tests/ --maxfail=1 --disable-warnings -q | tee test_output.log

      - name: Log error details if any issue occurs
        if: failure()
        run: |
          echo "⚠️ An error occurred during the CI run. Logging additional information..."
          echo "=== Environment Variables ==="
          printenv
          echo "=== Full Directory Listing ==="
          ls -alR
          echo "=== Installed Packages (pip freeze) ==="
          pip freeze
          echo "=== Test Output Log ==="
          cat test_output.log || echo "No test output log available."

      - name: Fail build if tests failed
        if: failure()
        run: exit 1
